# Numpy

Number Python

Verarbeitung von Zahlen (Winkelfunktionen, Rundungungsfunktionen, Zufallszahlen, ...)

In diesem Kurs werden Listen und Matrizen verarbeitet

In [1]:
import numpy as np

## Array

Effektiv wie list in Python, aber mehr wie ein klassisches Array

D.h., fixe Größe (kann nach Erstellung nicht vergrößert werden), ein Datentyp für alle Elemente

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
a

array([1, 2, 3, 4])

In [6]:
type(a)  # ndarray: n-dimensional array

numpy.ndarray

In [8]:
a.ndim  # Anzahl Dimensionen

1

In [10]:
a.shape  # XxY Größe

(4,)

In [12]:
a.dtype  # In Numpy gibt es effiziente Typen (int64 hier nicht optimal)

dtype('int64')

In [14]:
a.size  # Anzahl Gesamtelemente

4

In [16]:
len(a)  # Länge der ersten Dimension

4

### Datentypen

Ganze Zahlen:
- int8
- int16
- int32
- int64

Kommazahlen:
- float16
- float32
- float64

In [20]:
b = np.array([1, 2, 3, 4], dtype=np.int8)

In [19]:
b  # 1 Byte pro Zahl statt 8 Byte

array([1, 2, 3, 4], dtype=int8)

In [22]:
# np.array(["a", "b", "c"])  # Auch Zeichen möglich

In [27]:
np.arange(100)  # Array anhand einer Range erzeugen

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Matrizen

Ein Numpy Array mit 2 Dimensionen

In [46]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.int8)

In [47]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int8)

In [48]:
c.ndim

2

In [49]:
c.shape

(4, 3)

In [50]:
c.dtype

dtype('int8')

In [51]:
c.size

12

### Simple Funktionen

In [54]:
c.sum()

np.int64(78)

In [55]:
c.mean()

np.float64(6.5)

In [56]:
c.std()

np.float64(3.452052529534663)

In [57]:
c.var()

np.float64(11.916666666666666)

In [59]:
c[0].sum()  # Summiere die erste Zeile auf

np.int64(6)

### Index

Bei einer Matrix werden oftmals 2 Indizes benötigt

Der Numpy Index ist besser als der Python Index

In [60]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int8)

In [61]:
c[0][2]

np.int8(3)

In [63]:
c[0, 2]  # In Python nicht möglich

np.int8(3)

In [65]:
c[-1]  # Die letzte Zeile

array([10, 11, 12], dtype=int8)

In [68]:
c[0:2]  # Zeile 1 und 2 (oder 0 und 1)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [70]:
c[0:2, -1]  # Zeile 1 und 2 (oder 0 und 1), Spalte 2

array([3, 6], dtype=int8)

In [71]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int8)

In [78]:
# Aufgabe: 5, 8, 11 holen
c[1:4, 1]  # Obergrenze exkludiert, Zeile 1-4, Spalte 1

array([ 5,  8, 11], dtype=int8)

In [79]:
c[1:4, 1:3]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]], dtype=int8)

In [81]:
c[1:, 1:]  # Obergrenzen können weggelassen werden

array([[ 5,  6],
       [ 8,  9],
       [11, 12]], dtype=int8)

In [85]:
c[:3, :2]

array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int8)

In [92]:
c[:, 1]  # Alle Zeilen + Spalte 1

array([ 2,  5,  8, 11], dtype=int8)

#### axis

Mit axis kann eine Operation Zeilenbasiert oder Spaltenbasiert durchgeführt werden

In [96]:
c.sum(axis=0)  # Spaltenbasierte Summe

array([22, 26, 30])

In [98]:
c.sum(axis=1)  # Zeilenbasierte Summe

array([ 6, 15, 24, 33])

In [100]:
c.mean(axis=0)  # Spaltenbasierter Mittelwert

array([5.5, 6.5, 7.5])

#### Werte verändern

In [101]:
c[0, 0] = 10

In [102]:
c

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int8)

In [103]:
c[:, 1] = 0

In [104]:
c

array([[10,  0,  3],
       [ 4,  0,  6],
       [ 7,  0,  9],
       [10,  0, 12]], dtype=int8)

In [108]:
c[:, 1] = [-1, -1, -1, -1]

In [109]:
c

array([[10, -1,  3],
       [ 4, -1,  6],
       [ 7, -1,  9],
       [10, -1, 12]], dtype=int8)

## Vektorisierung

Jedes Element eines Arrays mit einer Operation bearbeiten

Z.B.: Addition, Subtraktion, ..., Boolesche Operatoren (<, >, ==, !=, <=, >=)

Wird für Filterung verwendet

In [110]:
d = np.arange(10)

In [111]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
d + 3  # Jedes Element um 3 erhöht

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [115]:
e = d + 3

In [116]:
e

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [118]:
d / 4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [124]:
d * np.arange(10)  # 2 Arrays miteinander vektorisieren

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [122]:
d ** d  # Array mit sich selbst vektorisieren

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

### Boolean Masken

Vektorisierung mit Booleschen Operatoren

Wird für Filterung verwendet

!!WICHTIG!!

In [125]:
f = np.arange(20)

In [126]:
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [128]:
f % 2 == 0  # Boolean Array

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [132]:
# Wenn jetzt dieses Ergebnisarray auf das Original vektorisiert wird, kommen nur die Zahlen heraus, die mit True kombiniert werden
x = f % 2 == 0
f[x]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [133]:
f > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [146]:
f[f % 2 == 0]  # Kurzform (ohne Variable)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Beispiel

In [137]:
y = np.random.randint(10, size=(20))

In [143]:
y

array([1, 3, 2, 9, 6, 9, 6, 2, 6, 2, 8, 8, 9, 5, 0, 1, 5, 0, 8, 7],
      dtype=int32)

In [138]:
y % 2 == 0

array([False, False,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False, False,  True,
        True, False])

In [139]:
y[y % 2 == 0]

array([2, 6, 6, 2, 6, 2, 8, 8, 0, 0, 8], dtype=int32)

In [142]:
np.arange(len(y))[y % 2 == 0]  # Stellen finden von den geraden Zahlen

array([ 2,  4,  6,  7,  8,  9, 10, 11, 14, 17, 18])

Beispiel 2

In [156]:
# Aufgabe: In y alle überdurchschnittlichen Werte finden
avg = y.mean()  # Durchschnitt finden
y > avg  # Boolean Maske
z = y > avg
y[z]  # Filterung

array([9, 6, 9, 6, 6, 8, 8, 9, 5, 5, 8, 7], dtype=int32)

In [154]:
y[y > y.mean()]  # Kurzform

array([9, 6, 9, 6, 6, 8, 8, 9, 5, 5, 8, 7], dtype=int32)

Filterung mit Matrix

In [157]:
c

array([[10, -1,  3],
       [ 4, -1,  6],
       [ 7, -1,  9],
       [10, -1, 12]], dtype=int8)

In [165]:
# Aufgabe: Alle Zeilen finden, die überdurchschnittlich sind
gesamtAvg = c.mean()
zeilenAvg = c.mean(axis=1)
zeilenAvg[zeilenAvg > gesamtAvg]

array([5., 7.])

In [166]:
zeilenAvg

array([4., 3., 5., 7.])

## Performance

In [169]:
from Grundkurs.M014 import measureTime

In [170]:
# Python
@measureTime
def pythonList():
    pList = list(range(100_000_000))

In [186]:
# Numpy
@measureTime
def numpyArray():
    nArray = np.arange(100_000_000, dtype=np.int32)

In [187]:
pythonList()

pythonList
2.58s


In [188]:
numpyArray()

numpyArray
0.138s


In [184]:
pList = list(range(100_000_000))  # 28 Byte pro Zahl = 2.8GB

In [185]:
del pList  # Nicht mehr benötigte Daten entfernen

## Weitere Funktionen

random

In [200]:
np.random.random()  # Zufallszahl zw. 0 und 1

0.6837380003925724

In [192]:
np.random.random(10)  # Array erzeugen

array([0.92316213, 0.47869716, 0.40663396, 0.51719954, 0.25261649,
       0.10486154, 0.60875257, 0.42137553, 0.39443683, 0.64633211])

In [195]:
np.random.randint(0, 10)  # Zufallszahl zw. 0 und 10 (ganze Zahl)

6

In [196]:
np.random.randint(0, 10, size=(10))

array([9, 0, 4, 4, 6, 4, 9, 5, 1, 9], dtype=int32)

In [199]:
np.random.randint(0, 10, size=(5, 5))

array([[1, 7, 3, 4, 9],
       [6, 2, 1, 4, 7],
       [3, 7, 7, 8, 8],
       [0, 7, 7, 7, 9],
       [1, 5, 4, 8, 5]], dtype=int32)

reshape

In [201]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [207]:
np.arange(10).reshape(-1, 1)  # Array senkrecht machen (Spalte anhängen an ein Datenset)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [208]:
r = np.arange(10).reshape(-1, 1)

In [211]:
r.reshape(-1)  # 2D-Array glätten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

linspace

Erzeugt ein Array von X bis Y mit Z Elementen, wobei jedes Element den gleichen Abstand hat

In [214]:
np.linspace(0, 10, 51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [213]:
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

zeros, ones

In [218]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [221]:
np.ones(10) == True  # Volle True Maske

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [219]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

hstack, vstack

Numpy Array an ein Datenset rechts/unten anhängen

Beispiel: Summenzeile/Summenspalte

In [222]:
s = np.random.randint(100, size=(5, 5))

In [223]:
s

array([[27,  6, 62, 49, 19],
       [ 7, 95, 11,  4, 14],
       [ 4, 84,  9, 33,  6],
       [37, 40, 30, 30, 30],
       [92, 95, 24,  9, 97]], dtype=int32)

In [229]:
# Aufgabe: Rechts + Unten eine Summe anhängen
s.sum(axis=0)

array([167, 320, 136, 125, 166])

In [231]:
v = np.vstack([s, s.sum(axis=0)])  # WICHTIG: Bei vstack/hstack müssen die Parameter in einer Liste sein

In [232]:
v

array([[ 27,   6,  62,  49,  19],
       [  7,  95,  11,   4,  14],
       [  4,  84,   9,  33,   6],
       [ 37,  40,  30,  30,  30],
       [ 92,  95,  24,   9,  97],
       [167, 320, 136, 125, 166]])

In [237]:
v.sum(axis=1)  # hstack kann nur 2D-Arrays anhängen -> reshape

array([163, 131, 136, 167, 317, 914])

In [238]:
v.sum(axis=1).reshape(-1, 1)

array([[163],
       [131],
       [136],
       [167],
       [317],
       [914]])

In [239]:
np.hstack([v, v.sum(axis=1).reshape(-1, 1)])

array([[ 27,   6,  62,  49,  19, 163],
       [  7,  95,  11,   4,  14, 131],
       [  4,  84,   9,  33,   6, 136],
       [ 37,  40,  30,  30,  30, 167],
       [ 92,  95,  24,   9,  97, 317],
       [167, 320, 136, 125, 166, 914]])